### ISSUE TITLE
Show npm install progress?

### ISSUE THREAD

**Issue by reintroducing** [dkundel/pkg-install#2]
Is there a way, when doing `install`, to show the progress that typically happens on an `npm install` while its installing? I tried using `verbose: true` but that did not output the install progress. It would be nice to be able to do that so that users don't see what looks like a frozen terminal if a lot of packages are installing.

**Comment by dkundel** [comment]
Hey @reintroducing! You should be able to pass to the config argument the `stdio` property. It accepts the same values as defined here: https://nodejs.org/api/child_process.html#child_process_options_stdio

So you should be able to do this and it should write it normally to the output:
`stdio: ['pipe', process.stdout, process.stderr]`

**Comment by reintroducing** [comment]
@dkundel Perfect, that worked like a charm, thanks so much!
