### ISSUE TITLE
Add support to 'npm --prefix'/'yarn --cwd' argument

### ISSUE THREAD

**Issue by mshima** [dkundel/pkg-install#3]
NPM looks for package.json at parent directory.
For some use cases would be nice to force npm to run on current dir.

**Comment by dkundel** [comment]
I'm definitely open for adding that support. But I would love to understand how that differs from the existing `cwd` option you can pass to `pkg-install` and what behavior you would expect if both are passed.

**Comment by mshima** [comment]
If you have a package with test dir.
When you run npm inside that dir, it will not find package.json there so it will look at the parent dir.
Without —prefix it’s not guaranteed package.json will be created/used at that specific folder.
https://docs.npmjs.com/misc/config#prefix

I really don’t know about yarn behavior.

**Comment by mshima** [comment]
An alternative is to always uses —prefix with cwd value.
I can help with a PR
